openapi: "3.0.2"
info:
  title: API REST Template
  version: "1.0"
servers:
  - url: https://api.template.test/v1
paths:
  /item:
    post:
      tags:
        - Items
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Item"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
    get:
      tags:
        - Items
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"
  /item/{id}:
    patch:
      tags:
        - Items
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The item ID
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Vendor"
    put:
      tags:
        - Items
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The item ID
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
    get:
      tags:
        - Items
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The item ID
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
  /vendor:
    post:
      tags:
        - Vendors
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Vendor"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Vendor"
    get:
      tags:
        - Vendors
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Vendor"
  /vendor/{id}:
    patch:
      tags:
        - Vendors
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The vendor ID
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Vendor"
    put:
      tags:
        - Vendors
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The vendor ID
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Vendor"
    get:
      tags:
        - Vendors
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The vendor ID
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Vendor"
  /warehouse:
    post:
      tags:
        - Warehouses
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Warehouse"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Warehouse"
    get:
      tags:
        - Warehouses
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Vendor"
  /warehouse/{id}:
    put:
      tags:
        - Warehouses
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The vendor ID
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Warehouse"
    patch:
      tags:
        - Warehouses
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The vendor ID
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Warehouse"
    get:
      tags:
        - Warehouses
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The vendor ID
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Warehouse"
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    Address:
      type: object
      properties:
        street:
          type: string
        city:
          type: string
        country:
          type: string
        zipCode:
          type: string
        phone:
          type: string
        email:
          type: string
    Vendor:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        address:
          $ref: "#/components/schemas/Address"
        items:
          type: array
          items:
            $ref: "#/components/schemas/Item"
    Warehouse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        address:
          $ref: "#/components/schemas/Address"
        items:
          type: array
          items:
            $ref: "#/components/schemas/Item"
